language: cpp
script: asdf plugin-test cmake https://github.com/srivathsanmurali/asdf-cmake.git
before_script:
  - git clone https://github.com/asdf-vm/asdf.git
  - . asdf/asdf.sh
os:
  - linux
  - osx
