name: reviewdog
on: [pull_request]
jobs:
  shellscript:
    name: runner / shellscript
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Check shellcheck error
        uses: reviewdog/action-shellcheck@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          path: "bin/"
          pattern: "*"
