---
name: Schedule workflow
on:
  schedule:
    - cron: "5 8/12 * * *"
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macOS-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: ruby setup (mac)
        if: ${{ matrix.os }} == 'macOS-latest'
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
      - name: asdf plugin test
        uses: asdf-vm/actions/plugin-test@v1
        env:
          GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          command: vim --version
